name: Hello Pipleline

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "👋 Hello, ${{github.actor}}! This is your first pipeline"

      - name: Show Date
        run: date

      - name: Run a Simple Script
        run: |
          echo "This is a bash script running inside CI"
          echo "Learning CI/CD is fun!"